import Navbar from "../components/Navbar";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MENU = [
  { id: 1, title: "Home", url: "/" },
  { id: 2, title: "About ", url: "/About" },
  { id: 3, title: "Cart", url: "/cart" },
  { id: 4, title: "Profile", url: "/Profile" },
  { id: 5, title: "FAQ", url: "/FAQ" },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <div className="layout">
          <Navbar list={MENU}/>
          {children}
        </div>
      </body>
    </html>
  );
}
